# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: 'mySQLdatabase'
    ServerName: 'uhpcdb-server.mysql.database.azure.com'
    DatabaseName: 'uhpcdb-database'
    SqlUsername: 'rgowfuefjv'
    SqlPassword: '3V611E02778Y6NT0$'
