name: MySQL for GitHub Actions

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
jobs:
    build:
        runs-on: windows-latest
        steps:
          
           - uses: azure/mysql@v1
             with:
                server-name: MYSQL_SERVER_NAME
                connection-string: ${{ secrets.AZURE_MYSQL_CONNECTION_STRING }}
                sql-file: './uhpcdb-database.sql'

            # Azure logout
           - name: logout
             run: |
              az logout
