# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 test-output:
   runs-on: ubuntu-latest
   steps:
       -name: Test output
       run: echo "Here is latest"
 connect-remote:
   runs-on: ubuntu-latest
   steps: 
   - uses: actions/checkout@v3
   - name: show database
     run: mysql -h ${{secrets.DB_HOSTNAME}} --port ${{secrets.DB_PORT}}  -u${{secrets.DB_USER}} --p${{secrets.DB_PASSWORD}}-e "SHOW DATABASE";
     
    
   

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
